### ISSUE TITLE
Unable to locate the ctld menu in the f10 menu.

### ISSUE THREAD

**Issue by hesc618** [ciribob/DCS-CTLD#114]
I want to use the auto jtac feature in the ctld script on my own server. After adding both mist and ctld scripts and successfully invoking jtac, I found that I couldn't see the expected ctld or jtac menu in the F10 menu. Additionally, when I tested with a test mission, I was also unable to find the F10 menu after spawning.

**Comment by davidp57** [comment]
That's probably because the unit you've spawned into is not part of CTLD.
There are multiple ways of correcting this, the easiest one is calling your unit "helicargo<xx>" where <xx> is a number between 1 and 25.
It's documented [here](https://github.com/ciribob/DCS-CTLD?tab=readme-ov-file#transport-unit-setup).
