### ISSUE TITLE
How to enable internal load and sling load at the same time?

### ISSUE THREAD

**Issue by Handsome1080P** [ciribob/DCS-CTLD#71]
How to enable internal load and sling load at the same time?If I modified this judge lines and only enable sling load,its correctly?

> Origin:if ctld.hoverPickup == false then
if ctld.slingLoad == false then
missionCommands.addCommandForGroup(_groupId, "Load Nearby Crate", _crateCommands, ctld.loadNearbyCrate,  _unitName )
end
end

> Modified:if ctld.hoverPickup == false then
missionCommands.addCommandForGroup(_groupId, "Load Nearby Crate", _crateCommands, ctld.loadNearbyCrate,  _unitName )
end
end

**Comment by StrykerCrow** [comment]
It's a few years late, but this here worked for me: 

-- line 45 -- ctld.loadCrateFromMenu = true
-- line 48 -- ctld.slingLoad = true
-- line 95 -- ctld.crateWaitTime = 0 -- otherwise you have to wait 120 secs to spawn the 2nd crate --
-- line 97 -- ctld.forceCrateToBeMoved = false -- if true, the sling loaded crate must be loaded first into the copter and then dropped again, otherwise wont unpack --
-- line 4923 -- if  ctld.slingLoad == true then
-- line 4930 -- if ctld.slingLoad == true then


I was able to load troops, load one crate internal and then hook up another crate via sling load. Could deploy everything. 
I think this is nice for the newly released Chinook. But for a Huey a bit too overpowered...
